<?php

namespace CareerBundle\Repository;

/**
 * FacultyDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacultyDepartmentRepository extends \Doctrine\ORM\EntityRepository
{
}
