<?php

namespace CareerBundle\Repository;

/**
 * SecurityUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecurityUserRepository extends \Doctrine\ORM\EntityRepository
{
}
