<?php

namespace CareerBundle\Repository;

/**
 * StudyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudyTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
